# -*- coding: utf-8 -*-
"""Revit Clash Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pn4GipooKEj82j16xM9cLfxQMEx4UCpL
"""

import codecs

from google.colab import files
uploaded = files.upload()

import IPython
from google.colab import drive
drive.mount('/drive')
IPython.display.HTML(filename='/drive/My Drive/Colab Notebooks/Clashs entre plomberie et ossature.html')

from bs4 import BeautifulSoup

with open("/drive/My Drive/Colab Notebooks/Clashs entre plomberie et ossature.html") as fp:
    soup = BeautifulSoup(fp, "html.parser")

import re
soup2=soup.find_all("td")
clashs = []
i=0
for elem in soup2 :
  if i>=3 :
    #s = "abc123AUG|GAC|UGAasdfg789"
    #print(type(elem))
    clashs.append(str(elem))
  i+=1
clashs

table = []
i=0
for elem in clashs :
  clashs_mod = elem.split('<td>')
  i+=1
  clash_final=clashs_mod[1].split('</td>')
  table.append(clash_final[0])
j=1
table2,table3,table4= [],[],[]
for elem in table :
  #table2.append(j)
  if j%3 != 0 :
    clash_final2=table[j].split(': id')
    table2.append(clash_final2)
  j+=1

k=1
for elem in table2 :
  for elem2 in elem :
    table3.append(elem2)
    if k%4 ==0:
      table4.append(table3)
      table3=[]
    k+=1
table4

import pandas as pd
import math as mt
df = pd.DataFrame(data = table4, columns = ['ElementX','IdX','ElementY','IdY'])
df

import pandas as pd
writer = pd.ExcelWriter('file.xlsx')
df.to_excel(writer, index = False)
writer.save()
files.download('file.xlsx')

